### PR TITLE
ANSA-340 Add contains and !contains operators for skiplogic

### PR DESCRIPTION
**Pull request by rcrichton**
ANSA-340

### CODE REVIEW

**Comment by BMartinos** [comment]
Thanks @rcrichton LGTM :+1:

**Comment by kaweesi** [comment]
@rcrichton how are these contains and !contains different from in and !in? CC @BMartinos

**Comment by rcrichton** [comment]
@kaweesi have a look at the comment in the readme.

**Comment by kaweesi** [comment]
could you point me to a skipLogic that uses this @rcrichton !!!

**Comment by rcrichton** [comment]
@kaweesi See the other PR in ANSA-340

**Pull request merged**
